stages:
  - name: shape
  - name: torso
    maxiters: 30
    shoulder_weight: 5.0
    hip_weight: 5.0
    initialize: true
  - name: pose
    maxiters: 15
  - name: pose2d
    maxiters: 15

maxiters: 15
shape_maxiters: 5
lbfgs_inner_max_iter: 8
enable_k2d_refine: true
k3d_robust_sigma: 0.05

loss_weights:
  k2d: 0.0001
  k3d: 1.0
  k3d_hand: 5.0
  k3d_face: 2.0
  joint_prior: 0.1
  reg_poses: 0.001
  reg_hand: 0.0001
  reg_head: 0.01
  reg_expr: 0.01
  reg_shapes: 0.005
  init_poses: 0.01
  init_shapes: 0.01
  s3d: 1.0
